resource_group_name   = "example-resources"
location              = "East US"
app_service_plan_name = "example-asp"
app_service_plan_tier = "Free"
app_service_plan_size = "F1"
web_app_name          = "example-webapp"
