name: Sync New Folders to Repo B

on:
  push:
    paths:
      - '**/'

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo A
        uses: actions/checkout@v3

      - name: Detect newly added folders
        id: detect
        run: |
          mkdir -p new_dirs
          git diff --name-status HEAD~1 HEAD | grep '^A' | awk '{print $2}' | \
          grep '/$' | cut -d/ -f1 | uniq > new_dirs/list.txt || true
          cat new_dirs/list.txt

      - name: Clone Repo B
        run: |
          git clone https://x-access-token:${{ secrets.REPO_B_PAT }}@github.com/AneerudhRa/repo-b-backup.git
          mv repo-b-backup repo_b

      - name: Copy new folders to Repo B
        run: |
          while read dir; do
            [ -d "$dir" ] && cp -r "$dir" repo_b/
          done < new_dirs/list.txt

      - name: Commit & Push to Repo B
        run: |
          cd repo_b
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add .
          git commit -m "Sync new folders from terraform_azure_modules"
          git push origin main
