name: Sync New Files/Folders to Repo B

on:
  push:
    paths:
      - '**'  # Trigger on any file or folder change

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo A
        uses: actions/checkout@v3

      - name: Detect newly added files/folders
        id: detect
        run: |
          mkdir -p new_paths
          git diff --name-status HEAD~1 HEAD | grep '^A' | awk '{print $2}' > new_paths/list.txt || true
          echo "Detected additions:"
          cat new_paths/list.txt

      - name: Clone Repo B
        run: |
          git clone https://x-access-token:${{ secrets.REPO_B_PAT }}@github.com/AneerudhRa/repo-b-backup.git
          mv repo-b-backup repo_b

      - name: Copy new files and folders to Repo B
        run: |
          while read path; do
            # Skip if file doesn't exist (just in case)
            [ -e "$path" ] && cp --parents -r "$path" repo_b/
          done < new_paths/list.txt

      - name: Commit & Push to Repo B
        run: |
          cd repo_b
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add .
          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            git commit -m "Sync new files/folders from terraform_azure_modules"
            git push origin main
          fi
